// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: session/session.proto

// old: protoc --go_out=plugins=grpc:. *.proto
// new: protoc --go_out=. --go-grpc_out=. session/*.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionID) Reset() {
	*x = SessionID{}
	mi := &file_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionID) ProtoMessage() {}

func (x *SessionID) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionID.ProtoReflect.Descriptor instead.
func (*SessionID) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Useragent     string                 `protobuf:"bytes,2,opt,name=useragent,proto3" json:"useragent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Session) GetUseragent() string {
	if x != nil {
		return x.Useragent
	}
	return ""
}

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         bool                   `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_session_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_session_session_proto_rawDescGZIP(), []int{2}
}

func (x *Nothing) GetDummy() bool {
	if x != nil {
		return x.Dummy
	}
	return false
}

var File_session_session_proto protoreflect.FileDescriptor

const file_session_session_proto_rawDesc = "" +
	"\n" +
	"\x15session/session.proto\x12\asession\"\x1b\n" +
	"\tSessionID\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"=\n" +
	"\aSession\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1c\n" +
	"\tuseragent\x18\x02 \x01(\tR\tuseragent\"\x1f\n" +
	"\aNothing\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\bR\x05dummy2\xa2\x01\n" +
	"\vAuthChecker\x120\n" +
	"\x06Create\x12\x10.session.Session\x1a\x12.session.SessionID\"\x00\x12/\n" +
	"\x05Check\x12\x12.session.SessionID\x1a\x10.session.Session\"\x00\x120\n" +
	"\x06Delete\x12\x12.session.SessionID\x1a\x10.session.Nothing\"\x00B\vZ\t./sessionb\x06proto3"

var (
	file_session_session_proto_rawDescOnce sync.Once
	file_session_session_proto_rawDescData []byte
)

func file_session_session_proto_rawDescGZIP() []byte {
	file_session_session_proto_rawDescOnce.Do(func() {
		file_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_session_proto_rawDesc), len(file_session_session_proto_rawDesc)))
	})
	return file_session_session_proto_rawDescData
}

var file_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_session_session_proto_goTypes = []any{
	(*SessionID)(nil), // 0: session.SessionID
	(*Session)(nil),   // 1: session.Session
	(*Nothing)(nil),   // 2: session.Nothing
}
var file_session_session_proto_depIdxs = []int32{
	1, // 0: session.AuthChecker.Create:input_type -> session.Session
	0, // 1: session.AuthChecker.Check:input_type -> session.SessionID
	0, // 2: session.AuthChecker.Delete:input_type -> session.SessionID
	0, // 3: session.AuthChecker.Create:output_type -> session.SessionID
	1, // 4: session.AuthChecker.Check:output_type -> session.Session
	2, // 5: session.AuthChecker.Delete:output_type -> session.Nothing
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_session_session_proto_init() }
func file_session_session_proto_init() {
	if File_session_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_session_proto_rawDesc), len(file_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_session_proto_goTypes,
		DependencyIndexes: file_session_session_proto_depIdxs,
		MessageInfos:      file_session_session_proto_msgTypes,
	}.Build()
	File_session_session_proto = out.File
	file_session_session_proto_goTypes = nil
	file_session_session_proto_depIdxs = nil
}
