// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: translit/translit.proto

// old: protoc --go_out=plugins=grpc:. *.proto
// new: protoc --go_out=. --go-grpc_out=. translit/*.proto

package translit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Word struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=Word,proto3" json:"Word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_translit_translit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_translit_translit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_translit_translit_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

var File_translit_translit_proto protoreflect.FileDescriptor

const file_translit_translit_proto_rawDesc = "" +
	"\n" +
	"\x17translit/translit.proto\x12\btranslit\"\x1a\n" +
	"\x04Word\x12\x12\n" +
	"\x04Word\x18\x01 \x01(\tR\x04Word2?\n" +
	"\x0fTransliteration\x12,\n" +
	"\x04EnRu\x12\x0e.translit.Word\x1a\x0e.translit.Word\"\x00(\x010\x01B\fZ\n" +
	"./translitb\x06proto3"

var (
	file_translit_translit_proto_rawDescOnce sync.Once
	file_translit_translit_proto_rawDescData []byte
)

func file_translit_translit_proto_rawDescGZIP() []byte {
	file_translit_translit_proto_rawDescOnce.Do(func() {
		file_translit_translit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translit_translit_proto_rawDesc), len(file_translit_translit_proto_rawDesc)))
	})
	return file_translit_translit_proto_rawDescData
}

var file_translit_translit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_translit_translit_proto_goTypes = []any{
	(*Word)(nil), // 0: translit.Word
}
var file_translit_translit_proto_depIdxs = []int32{
	0, // 0: translit.Transliteration.EnRu:input_type -> translit.Word
	0, // 1: translit.Transliteration.EnRu:output_type -> translit.Word
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_translit_translit_proto_init() }
func file_translit_translit_proto_init() {
	if File_translit_translit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translit_translit_proto_rawDesc), len(file_translit_translit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translit_translit_proto_goTypes,
		DependencyIndexes: file_translit_translit_proto_depIdxs,
		MessageInfos:      file_translit_translit_proto_msgTypes,
	}.Build()
	File_translit_translit_proto = out.File
	file_translit_translit_proto_goTypes = nil
	file_translit_translit_proto_depIdxs = nil
}
